version: 2
updates:
  # 1. Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix(deps)"
    open-pull-requests-limit: 5

  # 2. GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(actions)"
    open-pull-requests-limit: 3

  # 3. Kubernetes YAML manifests
  - package-ecosystem: "helm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(k8s)"
    open-pull-requests-limit: 3
