# Role for SAS Compute Work Purge
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sas-compute-work-purge-role
  namespace: {{ SAS-VIYA-NS }}
  annotations:
    sas.com/component-name: sas-compute-work-purge
  labels:
    sas.com/admin: cluster-wide
    sas.com/deployment: sas-viya
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "delete"]
- apiGroups: [""]
  resources: ["pods", "persistentvolumeclaims"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
# RoleBinding for SAS Compute Work Purge Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sas-compute-work-purge-rolebinding
  namespace: {{ SAS-VIYA-NS }}
  annotations:
    sas.com/component-name: sas-compute-work-purge
  labels:
    sas.com/admin: cluster-local
    sas.com/deployment: sas-viya
subjects:
- kind: ServiceAccount
  name: sas-programming-environment   # Ensure this service account exists with proper permissions.
  apiGroup: ""
roleRef:
  kind: Role
  name: sas-compute-work-purge-role   # Referencing the role defined above.
  apiGroup: rbac.authorization.k8s.io
---
##Optionally define the ServiceAccount if it doesn't exist.
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: sas-programming-environment
#  namespace: {{ SAS-VIYA-NS }}
#
#---

# Secret for storing OAuth credentials securely.
apiVersion: v1
kind: Secret
metadata:
  name: sas-compute-work-purge-creds
  namespace: {{ SAS-VIYA-NS }}
type: Opaque
data:
  client_id: {{ CLIENT-ID }}           # Ensure this is base64 encoded.
  client_secret: {{ CLIENT-SECRET }}   # Ensure this is base64 encoded.
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sas-compute-work-purge-job
  annotations:
    sas.com/component-name: sas-compute-work-purge
  labels:
    app.kubernetes.io/name: sas-compute-work-purge
    sas.com/admin: namespace
    sas.com/deployment: sas-viya
    workload.sas.com/class: compute    # Ensures this job runs on compute nodes.
spec:
  schedule: "0 * * * *"                # Runs every hour.
  successfulJobsHistoryLimit: 7        # Keeps history of last successful jobs.
  failedJobsHistoryLimit: 7            # Keeps history of last failed jobs.
  suspend: false                       # Ensures the job is not suspended.
  jobTemplate:
    metadata:
      annotations:
        sas.com/component-name: sas-compute-work-purge
      labels:
        app.kubernetes.io/name: sas-compute-work-purge
        sas.com/admin: namespace
        sas.com/deployment: sas-viya
    spec:
      template:
        metadata:
          annotations:
            sas.com/component-name: sas-compute-work-purge
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                  - key: workload.sas.com/class      # Ensures job runs on compute-class nodes.
                    operator: In
                    values:
                    - compute                        # Target compute nodes.
                weight: 100
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.azure.com/mode   # Avoid system nodes in Azure environments (if applicable).
                    operator: NotIn 
                    values:
                    - system
          containers:
          - name: sas-compute-work-purge
            image: ghcr.io/tonineri/sas-compute-work-purge:latest # for DEMO MODE (dry-run), use `image: antonioneri/sas-compute-work-purge:latestl-demo` instead
            imagePullPolicy: Always
            volumeMounts:
            - name: sas-work-dir
              mountPath: /sastmp
            env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: sas-compute-work-purge-creds 
                  key: client_id 
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sas-compute-work-purge-creds
                  key: client_secret 
            - name: TIME_LIMIT_HOURS                 # The age limit of a SAS Compute Server job. After a job reaches/exceeds the defined time limit, it will be marked for deletion.
              value: "{{ TIME-LIMIT-HOURS }}"
          restartPolicy: OnFailure
          tolerations:
          - effect: NoSchedule
            key: workload.sas.com/class
            operator: Equal
            value: compute
          serviceAccountName: sas-programming-environment
          volumes:
          - name: sas-work-dir
            ## Default to hostPath for /sastmp
            hostPath:                               # Comment this line if your SASWORK is PVC-based
              path: {{ SAS-WORK-HOSTPATH }}         # Comment this line if your SASWORK is PVC-based
            ## Optionally use a PVC
            #persistentVolumeClaim:                 # Uncomment this line if your SASWORK is PVC-based
            #  claimName: {{ SAS-WORK-PVC }}        # Uncomment this line if your SASWORK is PVC-based