---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sas-compute-work-purge-role
  namespace: {{ SAS-VIYA-NS }}
  annotations:
    sas.com/component-name: sas-compute-work-purge
  labels:
    sas.com/admin: cluster-wide
    sas.com/deployment: sas-viya
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "delete"]
- apiGroups: [""]
  resources: ["pods", "persistentvolumeclaims"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sas-compute-work-purge-rolebinding
  namespace: {{ SAS-VIYA-NS }}
  annotations:
    sas.com/component-name: sas-compute-work-purge
  labels:
    sas.com/admin: cluster-local
    sas.com/deployment: sas-viya
subjects:
- kind: ServiceAccount
  name: sas-programming-environment
  apiGroup: ""
roleRef:
  kind: Role
  name: sas-compute-work-purge-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Secret
metadata:
  name: sas-compute-work-purge-creds
  namespace: {{ SAS-VIYA-NS }}
type: Opaque
data:
  client_id: {{ CLIENT-ID }}
  client_secret: {{ CLIENT-SECRET }}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    sas.com/component-name: sas-compute-work-purge
  labels:
    app.kubernetes.io/name: sas-compute-work-purge
    sas.com/admin: namespace
    sas.com/deployment: sas-viya
    workload.sas.com/class: compute
  name: sas-compute-work-purge-job
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  suspend: false
  jobTemplate:
    metadata:
      annotations:
        sas.com/component-name: sas-compute-work-purge
      labels:
        app.kubernetes.io/name: sas-compute-work-purge
        sas.com/admin: namespace
        sas.com/deployment: sas-viya
        workload.sas.com/class: compute
    spec:
      template:
        metadata:
          annotations:
            sas.com/component-name: sas-compute-work-purge
          labels:
            sas.com/deployment: sas-viya
            workload.sas.com/class: compute
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                  - key: workload.sas.com/class
                    operator: In
                    values:
                    - compute
                  matchFields: []
                weight: 100
              - preference:
                  matchExpressions:
                  - key: workload.sas.com/class
                    operator: NotIn
                    values:
                    - stateless
                    - cas
                    - stateful
                  matchFields: []
                weight: 100
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.azure.com/mode
                    operator: NotIn
                    values:
                    - system
                  matchFields: []
          containers:
          - name: sas-compute-work-purge
            image: antonioneri/sas-compute-work-purge:latest
            imagePullPolicy: Always
            volumeMounts:
            - name: sas-work-dir
              mountPath: /sastmp
            env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: sas-compute-work-purge-creds 
                  key: client_id 
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sas-compute-work-purge-creds
                  key: client_secret 
            - name: TIME_LIMIT_HOURS
              value: "{{ TIME-LIMIT-HOURS }}"
            - name: SAS_VIYA_NS
              value: "{{ SAS-VIYA-NS }}"
          restartPolicy: OnFailure
          tolerations:
          - effect: NoSchedule
            key: workload.sas.com/class
            operator: Equal
            value: compute
          serviceAccountName: sas-programming-environment
          volumes:
          - name: sas-work-dir
            ## Default to hostPath for /sastmp
            hostPath:
              path: {{ SAS-WORK-HOSTPATH }}
            ## Optionally use a PVC
            #persistentVolumeClaim:
            #  claimName: {{ SAS-WORK-PVC }}
